# coding: utf-8

"""
    DeepLynx

    The construction of megaprojects has consistently demonstrated challenges for project managers in regard to meeting cost, schedule, and performance requirements. Megaproject construction challenges are common place within megaprojects with many active projects in the United States failing to meet cost and schedule efforts by significant margins. Currently, engineering teams operate in siloed tools and disparate teams where connections across design, procurement, and construction systems are translated manually or over brittle point-to-point integrations. The manual nature of data exchange increases the risk of silent errors in the reactor design, with each silent error cascading across the design. These cascading errors lead to uncontrollable risk during construction, resulting in significant delays and cost overruns. DeepLynx allows for an integrated platform during design and operations of mega projects. The DeepLynx Core API delivers a few main features. 1. Provides a set of methods and endpoints for manipulating data in an object oriented database. This allows us to store complex datatypes as records and then to compile them into actual, modifiable objects at run-time. Users can store taxonomies or ontologies in a readable format. 2. Provides methods for storing and retrieving data in a graph database. This data is structured and validated against the aformentioned object oriented database before storage.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest
import os
from dotenv import load_dotenv
import deep_lynx
from deep_lynx.models.create_manual_import import CreateManualImport
from deep_lynx.rest import ApiException

# Load environment variables
load_dotenv()

# Initialize configuration and API client
configuration = deep_lynx.configuration.Configuration()
configuration.host = os.getenv('BASE_URL')
api_client = deep_lynx.ApiClient(configuration)

# Initialize authentication API
auth_api = deep_lynx.AuthenticationApi(api_client)
api_key = os.getenv('API_KEY')
api_secret = os.getenv('API_SECRET')

# Get OAuth token
token = auth_api.retrieve_o_auth_token(x_api_key=api_key, x_api_secret=api_secret, x_api_expiry='1h')

class TestCreateManualImport(unittest.TestCase):
    """CreateManualImport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateManualImport(self):
        """Test CreateManualImport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = deep_lynx.models.create_manual_import.CreateManualImport()  # noqa: E501
        pass

if __name__ == '__main__':
    unittest.main()
